sunxi: fix CONFIG_REALTEK_PHY_HWMON build issue
Set missing CONFIG_REALTEK_PHY_HWMON=y as the default (as in main branch)
so that building (without V=s) doesn't fail with the error below : -

...
make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a
 higher verbosity level to see what's going on
make: *** [/home/jianni/openwrt-24.10/include/toplevel.mk:233: world] Error 1

Signed-off-by: Jianni Minicozzi <photonican@gmail.com>